src/ds3/ds3_mocks_test.go
src/ds3/models/abortMultipartResponse.go
src/ds3/models/badStatusCodeError.go
src/ds3/models/bulk.go
src/ds3/models/bulkGetResponse.go
src/ds3/models/bulkPutResponse.go
src/ds3/models/completeMultipartResponse.go
src/ds3/models/deleteBucketResponse.go
src/ds3/models/deleteObjectResponse.go
src/ds3/models/getBucketResponse.go
src/ds3/models/getObjectResponse.go
src/ds3/models/getServiceResponse.go
src/ds3/models/initiateMultipartResponse.go
src/ds3/models/listMultipartResponse.go
src/ds3/models/listPartsResponse.go
src/ds3/models/putBucketResponse.go
src/ds3/models/putObjectResponse.go
src/ds3/models/putPartResponse.go
src/ds3/models/responseHandling.go
src/ds3/networking/ds3request.go
src/ds3/networking/ds3response.go
src/ds3/networking/headers.go
src/ds3/networking/net.go
src/ds3_cli/commands/fileSizeReadCloser.go

**Changes**
- Renamed `Ds3Response` -> `WebResponse`
- Renamed `ContentMd5` -> `ContentHash` in header's `signatureFields` struct
- Renamed `fileSizeReadCloser` -> `fileWithSizeDecorator`
- Removed `io.Seeker` from `SizedReadCloser` interface
- Added error to return of `SizeReadCloser` interface and removed panic from `fileWithSizeDecorator` implementation
**TODO**
- Create Network decorators for network retry and 307 retry (and remove retry from network code)
- In headers, have `ContentHash` set via a header and passed to the `signatureFields`

Simple updates from Go review session

---

src/ds3/ds3.go
src/ds3/ds3_mocks_test.go
src/ds3/networking/httpredirect.go
src/ds3/networking/net.go
src/ds3/networking/networkerrors.go
src/ds3/networking/networkretry.go

**Changes**
- `HttpRedirectDecorator` wraps a `Network` and handles 307 redirects.
- `NetworkRetryDecorator` wraps a `Network` and handles retries due to network related issues.
- Removed retry logic from `httpNetwork`.

Network decorators

---

src/ds3/models/abortMultipartRequest.go
src/ds3/models/bulkGetRequest.go
src/ds3/models/bulkPutRequest.go
src/ds3/models/completeMultipartRequest.go
src/ds3/models/deleteBucketRequest.go
src/ds3/models/deleteObjectRequest.go
src/ds3/models/getBucketRequest.go
src/ds3/models/getObjectRequest.go
src/ds3/models/getServiceRequest.go
src/ds3/models/initiateMultipartRequest.go
src/ds3/models/listMultipartRequest.go
src/ds3/models/listPartsRequest.go
src/ds3/models/putBucketRequest.go
src/ds3/models/putObjectRequest.go
src/ds3/models/putPartRequest.go

The request handlers' query params were originally created and set within the getter function for query params.  I moved the initalization of query params into the request constructor, and moved the setting of querry parameters to relevant locations (within constructor and with-constructors).

Moved query param creation

---

src/ds3/ds3Client_test.go
src/ds3/ds3Mocks_test.go
src/ds3/models/bulk.go
src/ds3/models/bulkGetRequest.go
src/ds3/models/bulkPutRequest.go
src/ds3/models/completeMultipartRequest.go
src/ds3/networking/ds3Request.go
src/ds3_cli/commands/bulkPut.go
src/ds3_cli/commands/getBucket.go
src/ds3_cli/commands/getBucketObjects.go
src/ds3_integration/utils/testUtils.go

**Changes**
- Separated request and response payload models for bulk requests.
- Renamed models to conform with Java and Net SDK names
- Renamed `BuildSizedReadCloser` -> `BuildByteReaderWithSizeDecorator` which was missed when the associated struct name was updated.

Separated request and response models in preparation for autogen

---

src/ds3/models/bulk.go
src/ds3/models/completeMultipartRequest.go
src/ds3/models/requestPayloadUtils.go

**Changes**
- Created `requestPayloadUtil` which contains request payload models and converts those models into streams.
- `Ds3Object` struct, `ds3ObjectList` struct, and  `buildDs3ObjectListStream` method were moved from `bulk` to the new util class.
- WIthin `completeMultipartRequest`
- moved request payload's conversion to stream into the new util
- request struct modified to store content stream instead of `parts` for consistency

Created request payload util to convert requeset payloads into streams

---

src/ds3/ds3Client_test.go
src/ds3/models/abortMultipartResponse.go
src/ds3/models/badStatusCodeError.go
src/ds3/models/bulk.go
src/ds3/models/bulkGetResponse.go
src/ds3/models/bulkPutResponse.go
src/ds3/models/completeMultipartResponse.go
src/ds3/models/deleteBucketResponse.go
src/ds3/models/deleteObjectResponse.go
src/ds3/models/deleteObjectsResponse.go
src/ds3/models/getBucketResponse.go
src/ds3/models/getObjectResponse.go
src/ds3/models/getServiceResponse.go
src/ds3/models/initiateMultipartResponse.go
src/ds3/models/listMultipartResponse.go
src/ds3/models/listPartsResponse.go
src/ds3/models/putBucketResponse.go
src/ds3/models/putObjectResponse.go
src/ds3/models/putPartResponse.go
src/ds3/models/responseHandling.go

**Changes**
- Updated `checkStatusCode` to take multiple status codes so that a response handler can properly handle a 200 and 204 properly (for example)
- Updated response handling to use a switch statement for status codes to determine proper parsing. This was done in preparation for generating response handlers which have multiple non-error response codes

Updated response handler status code handling as prep for autogening

---

src/ds3/ds3Client.go
src/ds3/ds3Deletes.go
src/ds3/ds3Gets.go
src/ds3/ds3Posts.go
src/ds3/ds3Puts.go

**Changes**
- Made default max retries and max redirects constant rather than magic numbers
- Added network decorator `NetworkRetryDecorator` to all client commands
- Added network decorator `HttpTempRedirect` to all client commands of type GET except `GetObject`

Added network decorators in client code

---

src/ds3/ds3Client_test.go
src/ds3/ds3Gets.go
src/ds3/models/getJobToReplicateSpectraS3Request.go
src/ds3/models/getJobToReplicateSpectraS3Response.go
src/ds3/models/responseHandling.go

Implemented `GetJobToReplicateSpectraS3` command as prototype for how to generate responses with string response payloads

Implemented command with string response payload

---

src/ds3/ds3Client_test.go
src/ds3/models/listBucketResultParser.go
src/ds3/models/listMultiPartUploadsResultParser.go
src/ds3/models/responseParsingUtil.go

**Changes**
- Added unit test for parsing response payload with common prefixes
- Fixed how common prefixes is parsed
- Fixed inaccurate log message

SA-189: Fixed parsing of CommonPrefixes

---

src/ds3/ds3Client_test.go
src/ds3/models/clearSuspectBlobAzureTargetsSpectraS3Request.go
src/ds3/models/clearSuspectBlobPoolsSpectraS3Request.go
src/ds3/models/clearSuspectBlobS3TargetsSpectraS3Request.go
src/ds3/models/clearSuspectBlobTapesSpectraS3Request.go
src/ds3/models/ejectStorageDomainBlobsSpectraS3Request.go
src/ds3/models/getBlobsOnAzureTargetSpectraS3Request.go
src/ds3/models/getBlobsOnDs3TargetSpectraS3Request.go
src/ds3/models/getBlobsOnPoolSpectraS3Request.go
src/ds3/models/getBlobsOnS3TargetSpectraS3Request.go
src/ds3/models/getBlobsOnTapeSpectraS3Request.go
src/ds3/models/getBulkJobSpectraS3Request.go
src/ds3/models/getPhysicalPlacementForObjectsSpectraS3Request.go
src/ds3/models/getPhysicalPlacementForObjectsWithFullDetailsSpectraS3Request.go
src/ds3/models/markSuspectBlobAzureTargetsAsDegradedSpectraS3Request.go
src/ds3/models/markSuspectBlobDs3TargetsAsDegradedSpectraS3Request.go
src/ds3/models/markSuspectBlobPoolsAsDegradedSpectraS3Request.go
src/ds3/models/markSuspectBlobS3TargetsAsDegradedSpectraS3Request.go
src/ds3/models/markSuspectBlobTapesAsDegradedSpectraS3Request.go
src/ds3/models/putBulkJobSpectraS3Request.go
src/ds3/models/requestPayloadUtils.go
src/ds3/models/requestPayloadUtils_test.go
src/ds3/models/verifyBulkJobSpectraS3Request.go
src/ds3/models/verifyPhysicalPlacementForObjectsSpectraS3Request.go
src/ds3/models/verifyPhysicalPlacementForObjectsWithFullDetailsSpectraS3Request.go
src/ds3_cli/commands/bulkGet.go
src/ds3_cli/commands/bulkPut.go
src/ds3_cli/commands/getBucketObjects.go
src/ds3_integration/smoke_test.go
src/ds3_integration/utils/testUtils.go

**Changes**
- Divided `Ds3Object` into `Ds3PutObject`, `Ds3GetObject` and `Ds3VerifyObject` to properly represent request payloads.
- Simplified request payloads to use `[]string` whenever possible
- Added second constructor for `GetBulkJobSpectraS3Request` so that users can either specify request payload of `[]string` or `[]Ds3GetObject` for partial objects
- Added new request payload code for `<ids><id>id</id>...</ids>` which has appeared in 4.0
- Removed erroneous request payloads from some commands that have no payload
**Future Work**
- Update autogen to correctly generate all modified request handlers in this PR

Fixing request payloads new design

---

src/ds3/ds3Client_test.go
src/ds3/models/clearSuspectBlobS3TargetsSpectraS3Request.go
src/ds3/models/clearSuspectBlobTapesSpectraS3Request.go
src/ds3_utils/ds3Testing/assertUtil.go

**Changes**
- Added unit tests for all requests with payloads
- Test `TestVerifyPhysicalPlacementForObjectsWithFullDetailsSpectraS3` is commented out as there is a bug during response parsing which causes a panic. This test will be uncommented once the parsing bug is fixed.
- Fixed bug in assert util 
- Fixed get stream content in some manually modified request files in preparation for autogen fixes

Added unit tests for all requests with payloads

---

src/ds3_integration/smoke_test.go
src/ds3_integration/utils/testUtils.go

These unit tests cover the breadth of commands that will be used to extend the setup and teardown of the test environment used for integration testing.
**Future Changes**
Extend setup and teardown to include whole environment, so all unit tests can be run on an empty BP without any setup.

SDKPM-45: Added integration tests for commands to be used in test setup-teardown

---

src/ds3_integration/smoke_test.go
src/ds3_integration/utils/testUtils.go

The setup and teardown is based off of the Java integration setup and teardown code regarding what constitutes a robust environment.
**Tests**
All tests are passing. Tests run successfully if there is a default data policy, and if there is not a default data policy associated with the default user. If there exists a default data policy before running the tests, it is restored once tests are complete.

SDKPM-45: Created robust setup and teardown for integration tests

---

src/ds3/ds3Client_test.go
src/ds3/models/requestPayloadUtils.go
src/ds3/models/requestPayloadUtils_test.go
src/ds3/models/verifyBulkJobSpectraS3Request.go

**Changes**
- Fixed request payload for Verify Bulk to accept either a 'objectNames []string' or `objects []Ds3GetObject`
- Deleted erroneous `Ds3VerifyObject`
- Fixed unit test which was printing warnings due to incorrect expected response payload

SA-205: Fixed request payload for Verify Bulk and fixed minor bug in unit test

---

.travis.yml
README.md
ds3/ds3Client_test.go
samples/functions/getBucketSample.go
samples/functions/getBulkSample.go
samples/functions/getObjectSample.go
samples/functions/getServiceSample.go
samples/functions/putBulkSample.go
samples/samples.go
samples/utils/sampleUtils.go

- Adding travis yml file to enable unit tests in ds3 package to run on PRs. Unit tests are run with `go test` tool.
- Updated some improper format in tests that `go test` failed to compile with.

Adding travis yml and updating tests to work with go test

---

ds3/networking/httpRequestBuilder.go
ds3/networking/networking_test.go

Adding http headers that start with x-amz-meta- to authorization digest.  The header keys need to be sorted in ascending order.

Authorization digest

---

helpers/getTransfernator.go
helpers/helpersImpl.go
helpers/putTransceiver.go
helpers_integration/helpersImpl_test.go
helpers_integration/largeFileTestUtil.go

Returning the JobId will make diagnosing problems easier in the future.

Adding JobId as return value in helper put and get functions

---

helpers/putProducer.go
helpers_integration/helpersImpl_test.go

In the transfer blob operation, if we fail to get a reader, we should exit early. Previously we continued execution, and this caused a panic when we attempted to close the nil reader.

Fixing panic in put helper if file does not exist

---

ds3/ds3Client_test.go
ds3/models/responseModels.go
ds3/models/responseModels_test.go
ds3/models/responseParsingUtil.go

Instantiating optional enums in restore payloads before assigning value.

GOSDK-25: Unmarshaling optional enums in response payloads causes panic

---

helpers/channels/fatalErrorHandler.go
helpers/channels/objectReadChannelBuilder.go
helpers/channels/objectReadChannelDecorator.go
helpers/channels/objectWriteChannelBuilder.go
helpers/channels/partialObjectWriteChannelBuilder.go
helpers/getProducer.go
helpers/models/channelBuilder.go
helpers/putProducer.go
helpers_integration/helpersImpl_test.go
helpers_integration/largeFileTestUtil.go
helpers_integration/testReadChannels.go
helpers_integration/testWriteChannels.go

Extending channel builders to include a fatal error tracker. Now, if a fatal error happens on one blob, then channel builder is notified and future blobs associated with the same file are not transferred.

GOSDK-26: On archive helpers can hang indefinetely using streaming strategy if blob fails

---

ds3/networking/headers.go
ds3/networking/httpRequestBuilder.go
ds3/networking/httpRequestBuilder_test.go
ds3_integration/smoke_test.go

Even though `;` is a valid character in a URL according to the RFC spec, it does not play well with BP. Adding percent encoding for `;` and `+` in the path part of the URL.

NEO-1791: does not escape semicolon in outgoing PUT command to BlackPearl

---

ds3/networking/httpRequestBuilder_test.go
ds3_integration/smoke_test.go

Also, fixed logical bug in existing tests that was causing the retrieval step to be skipped.

NEO-2021: adding test for percent encoding horizontal tab character in file object name

---

helpers/getProducer.go
helpers/getTransfernator.go
helpers/listeners.go
helpers/putProducer.go
helpers/putTransceiver.go
helpers/readTransferStrategy.go
helpers/writeTransferStrategy.go
helpers_integration/helpersImpl_test.go
helpers_integration/largeFileTestUtil.go
helpers_integration/testStrategyUtils.go

Adding in a listener strategy for the helpers. This allows a callback to be specified for all errors that occur on a per-file basis. Removed the aggregate error that used to collect all errors that happened per-file. Now the PutObjects and GetObjects call return a simple error which affects the entire job only. Individual file errors must be retrieved via the new error callback.

GOSDK-18: Add object error and completed listeners to Strategies in helpers

---

helpers/getTransfernator.go
helpers/readTransferStrategy.go

It was a typo that some were package private.

OTHER: making all items in helper strategies public so that they can be set

---

helpers/blobStrategy.go
helpers/consumer.go
helpers/consumer_test.go
helpers/getProducer.go
helpers/getTransfernator.go
helpers/putProducer.go
helpers/putTransceiver.go

The problem is that we were busy waiting on GetJobChunksAvailable call. I'm switching the polling to happen on a timer or when a blob finishes instead of constantly hammering the BP.

GOSDK-28: When puts are in progress, the sdk logs are rolling every minute, 48k entries in that time

---

ds3/models/responseHandlingUtil.go
ds3/models/responses.go
ds3_integration/smoke_test.go

Closing all http response body's within the response structs to enusre it gets closed in error cases and when there is no request payload cases.

GOSDK-29: SDK leaks memory from unclosed HTTP response bodies

---

ds3_integration/utils/testUtils.go
helpers/conditionalBool.go
helpers/consumer.go
helpers/consumer_test.go
helpers/getProducer.go
helpers/getTransfernator.go
helpers/putProducer.go
helpers/putTransceiver.go
helpers_integration/helpersImpl_test.go

- Removed done channel which was causing go routines in the consumer to be left open longer than necessary
- Added thread safe done notification flag to replace done channel

GOSDK-32: System shutdown due to too many go routines when putting lots of files to BP

---

helpers/blobQueue.go

This only happens in streaming strategy combined with very small blob size on the BP bucket. There existed the possibility that a blob would be added to the queue twice. This explicitly prevents the double queuing of blobs.

OTHER: fixing race condition queueing things for processing. 

---

helpers/blobQueue.go

Cherry-pick (#101)
This only happens in streaming strategy combined with very small blob size on the BP bucket. There existed the possibility that a blob would be added to the queue twice. This explicitly prevents the double queuing of blobs.

OTHER: fixing race condition queueing things for processing

---

helpers/blobQueue.go

Cherry-pick (#101)
This only happens in streaming strategy combined with very small blob size on the BP bucket. There existed the possibility that a blob would be added to the queue twice. This explicitly prevents the double queuing of blobs.

OTHER: fixing race condition queueing things for processing.

---

ds3/models/ds3Response.go

Removing the to lower call on all headers which was messing with the MIME encoding.

GOSDK-23: The SDK breaks canonical MIME encoding of http headers

---

ds3/models/ds3Response.go

Cherry-pick (#110)
Removing the to lower call on all headers which was messing with the MIME encoding.

GOSDK-23: The SDK breaks canonical MIME encoding of http headers.

---

ds3_integration/utils/testUtils.go
helpers/getProducer.go
helpers_integration/helpersImpl_test.go

If the blob is not retrieved in its entirety, then ranged naked gets are used to retrieve the remaining portion of the blob. This retry only applies to blobs where no range was specified.

OTHER: adding retry around bulk get when a blob only partially transfers

---

ds3/networking/canonicalHeaders.go
ds3/networking/headers_test.go
ds3/networking/httpRequestBuilder.go
ds3_integration/smoke_test.go

The authorization header was being calculated incorrectly due to incorrect sorting on amz headers when there existed a header that started with an underscore. The `http.Header` implementation automatically camel cases headers. We were sorting the header keys before lower casing them when calculating the authorization header. Since underscore sorts differently when compared to upper and lower cased alpha characters, this created an incorrect sort order in the stringToSign. Fixed sorting to take place after lower casing header keys. 
Also fixed two stale tests that were failing due to unrelated issues.

Incorrect authorization header calculation

---

helpers/getTransfernator.go
helpers/helpersImpl.go
helpers/helpersImpl_test.go
helpers/ranges/rangeHelper.go

BP get jobs that specify IN_ORDER process guarantee can only be created if there exists enough cache available to pre-allocate the entire job. This makes the existing GetObjects helper not work when attempting to retrieve objects larger than available cache. Added a new helper function GetObjectsSpanningJobs that will break up large get jobs into multiple get jobs so very large files can still be retrieved.

OTHER: create helper to retrieve objects in-order that exceed available cache
